# Generated by Django 2.1.1 on 2018-10-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181003_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='last_name',
        ),
    ]
