# Generated by Django 2.1.1 on 2018-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181003_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user_details',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
